language: python

python:
  - 2.7

sudo: false

cache: pip

install:
  # Install SkyLines Python dependencies
  - pip install -e .

  # Install testing dependencies
  - pip install -r requirements.txt

script:
  # Generate asset files
  - ./setup.py install

  # Run the test suite
  #- py.test

notifications:
  email: yes
